---
- name: rename computer
  win_hostname:
    name: "W11HGAMING"
  register: rename_computer

- name: change power plan to high performance
  community.windows.win_power_plan:
    name: high performance
  register: hp

- name: windows update
  win_updates:
    category_names: ["*"]
    reboot: true
    reboot_timeout: '{{ global_delay }}'
  until: not windows_update.changed
  retries: 3
  delay: '{{ global_delay }}'

- name: nvidia display driver
  win_chocolatey:
    name: nvidia-display-driver
    state: latest
    params:
      '/NoAudio /NoUSBC'
  register: nvidia_display_driver
  until: nvidia_display_driver.rc == 0
  delay: '{{ global_delay }}'

- name: wsl2
  win_chocolatey:
    name: wsl2
    state: latest
  register: install_wsl2 

- name: reboot
  ansible.builtin.debug:
    msg: "reboot"
  changed_when: >
    rename_computer.changed or
    hp.changed or
    nvidia_display_driver.changed or
    install_wsl2.changed
  notify: reboot windows