---
- name: get local users
  win_shell: Get-LocalUser | Select-Object -ExpandProperty Name
  register: local_users

- name: remove unwanted users
  win_user:
    name: "{{ item }}"
    state: absent
  loop: "{{ local_users.stdout_lines }}"
  when:
    - item != ansible_user
    - item != "Administrator"
    - item != "DefaultAccount"
    - item != "Guest"
    - item != "WDAGUtilityAccount"

- name: remove unwanted users profiles
  win_file:
    path: C:\Users\{{ item }}
    state: absent
  loop: "{{ local_users.stdout_lines }}"
  when:
    - item != ansible_user
    - item != "Administrator"
    - item != "DefaultAccount"
    - item != "Guest"
    - item != "WDAGUtilityAccount"

- name: uninstall onedrive
  win_shell: cmd /c "{{ item }} /uninstall"
  loop:
    - C:\Windows\System32\OneDriveSetup.exe #32
    - C:\Windows\SysWOW64\OneDriveSetup.exe #64
  ignore_errors: true

- name: uninstall bloatware appx
  win_shell: |
    Get-AppxPackage *{{ item }}* | Remove-AppxPackage
  loop: "{{ bloatware_to_remove_appx }}"

- name: uninstall bloatware dism
  win_shell: |
    dism /Online /Disable-Feature /FeatureName:{{ item }} /NoRestart
  loop: "{{ bloatware_to_remove_dism }}"

- name: read HKCU run
  win_reg_stat:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
  register: runkey

- name: remove edge from HKCU run
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
    name: "{{ item }}"
    state: absent
  loop: "{{ runkey.properties | select('match', '^MicrosoftEdge') | list }}"